<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFEGkjZE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFEGkjZE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFEGkjZE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFEGkjZE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFEGkjZE\App_KernelDevDebugContainer([
    'container.build_hash' => 'FEGkjZE',
    'container.build_id' => '2dd2145b',
    'container.build_time' => 1749040678,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFEGkjZE');
