<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNU0haUn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNU0haUn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNU0haUn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNU0haUn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

<<<<<<< HEAD
return new \ContainerFEGkjZE\App_KernelDevDebugContainer([
    'container.build_hash' => 'FEGkjZE',
    'container.build_id' => '346cec78',
    'container.build_time' => 1749045586,
=======
return new \ContainerNU0haUn\App_KernelDevDebugContainer([
    'container.build_hash' => 'NU0haUn',
    'container.build_id' => 'bea98fe6',
    'container.build_time' => 1749048559,
>>>>>>> d8aa199001cfd8977bdca71390bc736ad4325d49
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNU0haUn');
